image: ruby:2.7.4

variables:
  TEST_PATH: "nyanTest"
  TEST_FILES: "nyanTest/testCode"

stages:
  - build
  - test
  - deploy

before_script:
  - gem install bundler -v 2.4.22

build:
  stage: build
  script:
    - bundle install --jobs $(nproc) --path vendor

conditions:
  stage: test
  script:
    - ruby -Itest $TEST_PATH/testConditions.rb

scope:
  stage: test
  script:
    - ruby -Itest $TEST_PATH/testScope.rb

syntaxtree:
  stage: test
  script:
    - ruby -Itest $TEST_PATH/testSyntaxtree.rb

nyan_conditions:
  stage: deploy
  script:
    - ruby


# test:
#   stage: test
#   script:
#     - ruby -v  # Print Ruby version for debugging purposes
#     - find . -type f -name "nyanTest/test*.rb" | while read test_file; do
#         echo "Running tests in $test_file";
#         ruby -Itest $test_file || exit 1;
#       done
    # - ruby -Itest nyanTest/*.rb