image: ruby:2.7.4

variables:
  TEST_PATH: "nyanTest"
  TEST_FILES: "nyanTest/testFiles"

stages:
  - build
  - test
  - deploy

before_script:
  - gem install bundler -v 2.4.22

build:
  stage: build
  script:
    - bundle install --jobs $(nproc) --path vendor

flags:
  stage: test
  script:
    - ruby nyan.rb -h
    - ruby nyan.rb -v
    - ruby nyan.rb $TEST_FILES/simplePrint.nyan
    - ruby nyan.rb $TEST_FILES/simplePrint.nyan -d on
  rules:
    - when: manual

conditions:
  stage: test
  script:
    - ruby -Itest $TEST_PATH/testConditions.rb
  rules:
    - when: manual

scope:
  stage: test
  script:
    - ruby -Itest $TEST_PATH/testScope.rb
  rules:
    - when: manual

syntaxtree:
  stage: test
  script:
    - ruby -Itest $TEST_PATH/testSyntaxtree.rb
  rules:
    - when: manual

parser:
  stage: test
  script: 
    - ruby -Itest $TEST_PATH/testParser.rb

nyan_conditions:
  stage: deploy
  script:
    - ruby nyan.rb $TEST_FILES/conditions.nyan
    #- ruby nyan.rb $TEST_FILES/functions.nyan
  rules:
    - when: manual


# test:
#   stage: test
#   script:
#     - ruby -v  # Print Ruby version for debugging purposes
#     - find . -type f -name "nyanTest/test*.rb" | while read test_file; do
#         echo "Running tests in $test_file";
#         ruby -Itest $test_file || exit 1;
#       done
    # - ruby -Itest nyanTest/*.rb