image: ruby:latest

stages:
  - test

before_script:
  - gem install bundler -v 2.4.22
  - bundle install --jobs $(nproc) --path vendor

rspec:
  stage: test
  script:
    - ruby -Itest nyanTest/testSyntaxtree.rb